/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import koneksi.Koneksi;

/**
 *
 * @author nineone
 */
public class fCetak extends javax.swing.JFrame {

//    public String noKTP = new fPelanggan().kirim();
    public String noKTP;
    private Connection conn = new Koneksi().connect();
    /**
     * Creates new form fCetak
     */
    public fCetak( String input) {
        initComponents();
        noKTP = input;
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lembarPrint = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        noTransaksi = new javax.swing.JLabel();
        tglKembali = new javax.swing.JLabel();
        tglSewa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelKTP = new javax.swing.JLabel();
        labelJK = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelTelp = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelMobil = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelPlat = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        labelNamaSopir = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelTelpSopir = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        labelSewa = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        namaTerang = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        labelKet = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));

        lembarPrint.setBackground(new java.awt.Color(197, 197, 197));
        lembarPrint.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lembarPrint.setForeground(new java.awt.Color(94, 114, 122));
        lembarPrint.setPreferredSize(new java.awt.Dimension(676, 620));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo Family Rental.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(149, 166, 176));
        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(69, 79, 101));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FAMILY RENTAL");

        jLabel3.setBackground(new java.awt.Color(149, 166, 176));
        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 79, 101));
        jLabel3.setText("Rental Mobil Keluarga Termurah di Jember");

        noTransaksi.setBackground(new java.awt.Color(149, 166, 176));
        noTransaksi.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        noTransaksi.setForeground(new java.awt.Color(69, 79, 101));
        noTransaksi.setText("No. Transaksi :");

        tglKembali.setBackground(new java.awt.Color(149, 166, 176));
        tglKembali.setForeground(new java.awt.Color(69, 79, 101));
        tglKembali.setText("Tanggal Kembali :");

        tglSewa.setBackground(new java.awt.Color(149, 166, 176));
        tglSewa.setForeground(new java.awt.Color(69, 79, 101));
        tglSewa.setText("Tanggal Masuk :");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(254, 254, 254));

        jLabel7.setBackground(new java.awt.Color(149, 166, 176));
        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(69, 79, 101));
        jLabel7.setText("A. IDENTITAS PELANGGAN");

        jLabel8.setBackground(new java.awt.Color(149, 166, 176));
        jLabel8.setForeground(new java.awt.Color(69, 79, 101));
        jLabel8.setText("Nama       :");

        jLabel9.setBackground(new java.awt.Color(149, 166, 176));
        jLabel9.setForeground(new java.awt.Color(69, 79, 101));
        jLabel9.setText("No. KTP          :");

        jLabel10.setBackground(new java.awt.Color(149, 166, 176));
        jLabel10.setForeground(new java.awt.Color(69, 79, 101));
        jLabel10.setText("Jenis Kelamin :");

        jLabel11.setBackground(new java.awt.Color(149, 166, 176));
        jLabel11.setForeground(new java.awt.Color(69, 79, 101));
        jLabel11.setText("No. Telepon   :");

        jLabel12.setBackground(new java.awt.Color(149, 166, 176));
        jLabel12.setForeground(new java.awt.Color(69, 79, 101));
        jLabel12.setText("Alamat            :");

        labelNama.setBackground(new java.awt.Color(149, 166, 176));
        labelNama.setForeground(new java.awt.Color(69, 79, 101));
        labelNama.setText(" ");

        labelKTP.setBackground(new java.awt.Color(149, 166, 176));
        labelKTP.setForeground(new java.awt.Color(69, 79, 101));
        labelKTP.setText(" ");

        labelJK.setBackground(new java.awt.Color(149, 166, 176));
        labelJK.setForeground(new java.awt.Color(69, 79, 101));
        labelJK.setText(" ");

        labelAlamat.setBackground(new java.awt.Color(149, 166, 176));
        labelAlamat.setForeground(new java.awt.Color(69, 79, 101));
        labelAlamat.setText(" ");

        labelTelp.setBackground(new java.awt.Color(149, 166, 176));
        labelTelp.setForeground(new java.awt.Color(69, 79, 101));
        labelTelp.setText(" ");

        jLabel13.setBackground(new java.awt.Color(149, 166, 176));
        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(69, 79, 101));
        jLabel13.setText("B. DATA MOBIL");

        jLabel14.setBackground(new java.awt.Color(149, 166, 176));
        jLabel14.setForeground(new java.awt.Color(69, 79, 101));
        jLabel14.setText("Mobil              :");

        labelMobil.setBackground(new java.awt.Color(149, 166, 176));
        labelMobil.setForeground(new java.awt.Color(69, 79, 101));
        labelMobil.setText(" ");

        jLabel15.setBackground(new java.awt.Color(149, 166, 176));
        jLabel15.setForeground(new java.awt.Color(69, 79, 101));
        jLabel15.setText("No. Plat          :");

        labelPlat.setBackground(new java.awt.Color(149, 166, 176));
        labelPlat.setForeground(new java.awt.Color(69, 79, 101));
        labelPlat.setText(" ");

        jLabel16.setBackground(new java.awt.Color(149, 166, 176));
        jLabel16.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(69, 79, 101));
        jLabel16.setText("C. DATA SOPIR");

        jLabel17.setBackground(new java.awt.Color(149, 166, 176));
        jLabel17.setForeground(new java.awt.Color(69, 79, 101));
        jLabel17.setText("Nama             :");

        labelNamaSopir.setBackground(new java.awt.Color(149, 166, 176));
        labelNamaSopir.setForeground(new java.awt.Color(69, 79, 101));
        labelNamaSopir.setText(" ");

        jLabel18.setBackground(new java.awt.Color(149, 166, 176));
        jLabel18.setForeground(new java.awt.Color(69, 79, 101));
        jLabel18.setText("No. Telepon  :");

        labelTelpSopir.setBackground(new java.awt.Color(149, 166, 176));
        labelTelpSopir.setForeground(new java.awt.Color(69, 79, 101));
        labelTelpSopir.setText(" ");

        labelTotal.setBackground(new java.awt.Color(149, 166, 176));
        labelTotal.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(69, 79, 101));
        labelTotal.setText("Total : ");

        jLabel19.setBackground(new java.awt.Color(149, 166, 176));
        jLabel19.setForeground(new java.awt.Color(69, 79, 101));
        jLabel19.setText("Sewa :");

        labelSewa.setBackground(new java.awt.Color(149, 166, 176));
        labelSewa.setForeground(new java.awt.Color(69, 79, 101));
        labelSewa.setText(" ");

        jLabel23.setBackground(new java.awt.Color(149, 166, 176));
        jLabel23.setForeground(new java.awt.Color(69, 79, 101));
        jLabel23.setText("Hari");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel15)
                                .addComponent(jLabel18))))
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotal)
                    .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKTP, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelJK, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNamaSopir, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTelpSopir, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(labelKTP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelJK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelTelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(labelAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(labelMobil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(labelPlat)
                    .addComponent(jLabel19)
                    .addComponent(labelSewa)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(labelNamaSopir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(labelTelpSopir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(labelTotal)
                .addContainerGap())
        );

        jLabel5.setBackground(new java.awt.Color(149, 166, 176));
        jLabel5.setForeground(new java.awt.Color(69, 79, 101));
        jLabel5.setText("Tanda Terima,");

        jLabel6.setBackground(new java.awt.Color(149, 166, 176));
        jLabel6.setForeground(new java.awt.Color(69, 79, 101));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("..............");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        namaTerang.setBackground(new java.awt.Color(149, 166, 176));
        namaTerang.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        namaTerang.setForeground(new java.awt.Color(69, 79, 101));
        namaTerang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaTerang.setText("(Nama Terang)");
        namaTerang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel20.setBackground(new java.awt.Color(149, 166, 176));
        jLabel20.setForeground(new java.awt.Color(69, 79, 101));
        jLabel20.setText("Hormat Kami,");

        jLabel22.setBackground(new java.awt.Color(149, 166, 176));
        jLabel22.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(69, 79, 101));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("ADMIN");
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel24.setBackground(new java.awt.Color(149, 166, 176));
        jLabel24.setForeground(new java.awt.Color(69, 79, 101));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("..............");
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelKet.setBackground(new java.awt.Color(25, 103, 224));
        labelKet.setFont(new java.awt.Font("Noto Sans", 3, 18)); // NOI18N
        labelKet.setText("jLabel4");

        javax.swing.GroupLayout lembarPrintLayout = new javax.swing.GroupLayout(lembarPrint);
        lembarPrint.setLayout(lembarPrintLayout);
        lembarPrintLayout.setHorizontalGroup(
            lembarPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lembarPrintLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lembarPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lembarPrintLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(lembarPrintLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(lembarPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lembarPrintLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel2))
                            .addGroup(lembarPrintLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(labelKet)
                        .addGap(63, 63, 63))
                    .addGroup(lembarPrintLayout.createSequentialGroup()
                        .addComponent(noTransaksi)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(lembarPrintLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(lembarPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaTerang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lembarPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lembarPrintLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglSewa)
                .addGap(168, 168, 168)
                .addComponent(tglKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lembarPrintLayout.setVerticalGroup(
            lembarPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lembarPrintLayout.createSequentialGroup()
                .addGroup(lembarPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lembarPrintLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(lembarPrintLayout.createSequentialGroup()
                        .addGroup(lembarPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lembarPrintLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lembarPrintLayout.createSequentialGroup()
                                .addComponent(labelKet)
                                .addGap(33, 33, 33)))
                        .addComponent(noTransaksi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lembarPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglSewa)
                    .addComponent(tglKembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lembarPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(lembarPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel24))
                .addGap(2, 2, 2)
                .addGroup(lembarPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaTerang)
                    .addComponent(jLabel22))
                .addGap(33, 33, 33))
        );

        btnCetak.setBackground(new java.awt.Color(50, 214, 34));
        btnCetak.setForeground(new java.awt.Color(214, 34, 46));
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/check.png"))); // NOI18N
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lembarPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCetak)
                .addGap(331, 331, 331))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lembarPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
//        print(lembarPrint);
        print(lembarPrint);
//        PrinterJob pj = PrinterJob.getPrinterJob();
//        pj.setJobName(" Print Nota ");
//        
//        
//        
//        if (pj.printDialog() == false) return;
//        
//        try {
//            pj.setPrintService((PrintService) lembarPrint);
//            pj.print();
//        } catch (Exception e) {
//            System.err.println(e);
//        }
    }//GEN-LAST:event_btnCetakActionPerformed

//    public void print(Component component){
//        PrinterJob pj = PrinterJob.getPrinterJob();
//        pj.setJobName(" Print Nota ");
//        
//        pj.setPrintable (new Printable(){
//            public int print(Graphics pg, PageFormat pf, int pageNum){
//                if (pageNum > 0) return Printable.NO_SUCH_PAGE;
//                
//                Graphics2D g2 = (Graphics2D) pg;
//                g2.translate(pf.getImageableX(), pf.getImageableY());
//                component.paint(g2);
//                return Printable.PAGE_EXISTS;
//            }
//        });
//        
//        if (pj.printDialog() == false) return;
//        
//        try {
//            pj.print();
//        } catch (Exception e) {
//            System.err.println(e);
//        }
//    }
    
    public void print(JPanel panel){
        // Create PrinterJob Here
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        // Set Printer Job Name
        printerJob.setJobName("Print Record");
        // Set Printable
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                // Check If No Printable Content
                if(pageIndex > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                // Make 2D Graphics to map content
                Graphics2D graphics2D = (Graphics2D)graphics;
                // Set Graphics Translations
                // A Little Correction here Multiplication was not working so I replaced with addition
                graphics2D.translate(pageFormat.getImageableX()+10, pageFormat.getImageableY()+10);
                // This is a page scale. Default should be 0.3 I am using 0.5
                graphics2D.scale(0.5, 0.5);
                
                // Now paint panel as graphics2D
                panel.paint(graphics2D);
                
                // return if page exists
                return Printable.PAGE_EXISTS;
            }
        });
        // Store printerDialog as boolean
        boolean returningResult = printerJob.printDialog();
        // check if dilog is showing
        if(returningResult){
            // Use try catch exeption for failure
            try{
                // Now call print method inside printerJob to print
                printerJob.print();
            }catch (PrinterException printerException){
                JOptionPane.showMessageDialog(this, "Print Error: " + printerException.getMessage());
            }
        }
    }
    private void tampilkan() {
        try {
            ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM pelanggan "
                    + "WHERE no_ktp = '" + noKTP + "'");
            while (rs.next()) {
                    noTransaksi.setText("No. Transaksi : " + rs.getString(1));
                    tglSewa.setText("Tanggal Masuk : " + rs.getString(12));
                    tglKembali.setText("Tanggal Kembali : " + rs.getString(13));
                    
                    labelNama.setText(rs.getString(3));
                    labelKTP.setText(rs.getString(2));
                    labelJK.setText(rs.getString(4));
                    labelTelp.setText(rs.getString(5));
                    labelAlamat.setText(rs.getString(6));
                    
                    labelMobil.setText(rs.getString(8));
                    labelPlat.setText(rs.getString(9));
                    labelSewa.setText(rs.getString(7));
                    
                    labelNamaSopir.setText(rs.getString(10));
                    labelTelpSopir.setText(rs.getString(11));
                    
                    labelTotal.setText("Total : Rp. " + rs.getString(14));
                    
                    labelKet.setText(rs.getString(15));
                    
                    namaTerang.setText("(" + rs.getString(3) + ")");
            }
            System.out.println("Koneksi Berhasil");
        } catch (SQLException ex) {
            Logger.getLogger(fPelanggan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Data Gagal dipanggil " + ex);
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(fCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(fCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(fCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(fCetak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new fCetak().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelJK;
    private javax.swing.JLabel labelKTP;
    private javax.swing.JLabel labelKet;
    private javax.swing.JLabel labelMobil;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNamaSopir;
    private javax.swing.JLabel labelPlat;
    private javax.swing.JLabel labelSewa;
    private javax.swing.JLabel labelTelp;
    private javax.swing.JLabel labelTelpSopir;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPanel lembarPrint;
    private javax.swing.JLabel namaTerang;
    private javax.swing.JLabel noTransaksi;
    private javax.swing.JLabel tglKembali;
    private javax.swing.JLabel tglSewa;
    // End of variables declaration//GEN-END:variables
}
